name: wazo-plugin-survey-feedback
namespace: quintana
version: 0.0.1
author: Piotr
display_name: Plugin Demo
plugin_format_version: 1
min_wazo_version: 25.12
tags:
  - community
  - demo
debian_depends:
  - vim
homepage: https://github.com/darkhorse34/demo-plugin